Create initial experimental omega_edit UI.
ctc-oss/daffodil-vscode pull request #59
Opened 2022-04-28 21:34 UTC by Shanedell

To use the experimental omega_edit UI:

- open the command palette via `Command + Shift + P` (mac/linux) or `Ctrl + Shift + P` (windows).
- type `omega.exp.grpc` and hit `Enter`

You will be prompted to open select a file to open. Currently offset, encoded and decoded sections of the UI are connected with code so the result of those will vary depending on file. None of the boxes are currently editable either it was mostly a frame up of the UI the interactive aspect will come later.

2022-04-28 21:38 UTC, Shanedell commented
@scholarsmate Is #40 necessary? This would be available by default from VS Code. So if you copy something from a web browser and paste into an editable element it would be pasted fine I believe so I am not sure the ticket is needed.

2022-04-29 11:54 UTC, scholarsmate commented
> @scholarsmate Is #40 necessary? This would be available by default from VS Code. So if you copy something from a web browser and paste into an editable element it would be pasted fine I believe so I am not sure the ticket is needed.

@Shanedell, that is a requirement of the application.  If we "get it for free" by virtue of VSCode, that's good, but we'll need to demonstrate that the requirement is met before we close any of these.  If we close it with no code changes, be sure to describe how the requirement is being met by the application.

2022-04-29 12:20 UTC, scholarsmate requested changes
Essentially lots of name changes to align with the naming guide.

2022-04-29 12:20 UTC, scholarsmate commented on package.json
> +        "title": "Omega Edit Ω Experiment Version Info",
Title should read: Ωedit Version Info.  Drop experiment since we're going to increment this along to be production.

2022-04-29 12:20 UTC, scholarsmate commented on package.json
> +        "title": "Omega Edit Ω Experiment gRPC Demo",
Title should read: Ωedit Demo.  gRPC is a middle-ware detail that no one needs to know about.

2022-04-29 12:20 UTC, scholarsmate commented on package.json
> +        "category": "Omega"
OmegaEdit would be the preferred choice here.

2022-04-29 12:20 UTC, scholarsmate commented on package.json
> +        "category": "Omega"
OmegaEdit would be the preferred choice here.

2022-04-29 12:20 UTC, scholarsmate commented on package.json
> +          "command": "omega.exp.grpc"
These prefixes should be omega_edit or omega-edit, not just omega, and what do you think about dropping the .exp part?

2022-04-29 12:20 UTC, scholarsmate commented on src/adapter/activateDaffodilDebug.ts
> +import * as omegaClientExp from '../omega_edit/client-exp'
omegaEditClient / omegaEditClientExp here.

2022-04-29 12:20 UTC, scholarsmate commented on src/omega_edit/client-exp.ts
> +      let vpin = await createViewport(randomId().toString(), s, 0, 1000)
You can name these viewports like "vpin", "vp1", "vp2", etc instead of using a random ID (they just need to be unique per session).  Also, if you really do want a random ID, you can pass null in for the ID and Ωedit will generate a UUID for you.

2022-04-29 12:20 UTC, scholarsmate commented on src/omega_edit/client-exp.ts
> +    <title>Omega gRPC</title>
Title: Ωedit.  We can drop the gRPC since that's a middle-ware detail no one needs to know up here on the front-end.

2022-04-29 14:06 UTC, scholarsmate commented
I think we remove the "experimental" here because we'll increment this work to become the data view / data editor component of the DFDL extension.

We don't need to advertise Ωedit anywhere in the user-visible front-end because end-users are not going to care (it's a back-end detail) and will only cause confusion.  The front-end users care about the functionality being provided, and not about how or what is providing the functionality.  If they are curious developers, they can consult the source code for the how and the what.

2022-04-29 16:18 UTC, scholarsmate approved these changes

2022-04-29 16:53 UTC, merged