Initial Viewport editing support
ctc-oss/daffodil-vscode pull request #69
Opened 2022-05-10 22:04 UTC by Shanedell

Updates:

- Disable all omega_edit related commands disabled by default
  - To enable you need to run `toggle.enableExperimentalFeatures`
- Makes viewports editable when using the `data.edit` command
- Copy and Paste work using OS clipboard using normal shortcut keys
- Undo and Redo work using OS shortcut keys

Bugs:

- Currently there are issues with the syncing from the 3 smaller viewports to the largest viewport and the largest viewport to the 3 smaller viewports. However this depends on the which one you start editing first. If you off the beginning if you only edit the 3 smaller viewports the syncing works fine. If you start off editing ONLY the largest viewport (has all the data of the file) sync works fine. The bug in syncing happens when you start with editing one or the other that switch to the other one.
- Deletetion not fully working where if something was pushed out it does not came back upon deletion of data before it.

Closes #21 
Closes #23 
Closes #38
Closes #39 
Closes #40 

@scholarsmate I believe this closes mostly everything except for deletion. As the video display it is able to delete successfully but refreshing the viewport data just needs fixed

Demo GIF:

![sampleWorkspace-1652219958514](https://user-images.githubusercontent.com/32347414/167729115-b8738e15-d5ea-4b60-8e48-24cbc3c24a63.gif)

2022-05-10 22:51 UTC, scholarsmate requested changes
This doesn't appear to be plumbed correctly to me.

2022-05-10 22:51 UTC, scholarsmate commented on src/omega_edit/client.ts
> +              change.setLength(message.capacity)
I'm not clear on what's happening here.  It appears that we're always doing overwrites and I don't think message.offset and message.capacity are the right things here.  This might be trying to send the entire thing to the backend each time which is not a good idea.  It will chew up memory making a copy of the whole thing for each change.

2022-05-10 22:51 UTC, scholarsmate commented on src/omega_edit/client.ts
> +      <div class="grid-item"><textarea id="vpAll" rows="10" cols="50" oninput="sendit(this.value, 0, 1000)"></textarea></div>
We'll need this to be more dynamic.

2022-05-10 22:51 UTC, scholarsmate commented on src/omega_edit/scripts/omega_edit.js
> +    capacity: capacity,
I'm worried about capacity here.  I'll need to look more carefully at what this is doing in the middleware and the backend.  I really don't think this is what we want.

2022-05-10 23:31 UTC, Shanedell commented on src/omega_edit/client.ts
> +              change.setLength(message.capacity)
This is basically setting the offset and length of the viewport being changed

2022-05-10 23:32 UTC, Shanedell commented on src/omega_edit/client.ts
> +      <div class="grid-item"><textarea id="vpAll" rows="10" cols="50" oninput="sendit(this.value, 0, 1000)"></textarea></div>
What do you mean? I will be more dynamic I believe in the long run once we get the other UI fully working

2022-05-10 23:33 UTC, Shanedell commented on src/omega_edit/scripts/omega_edit.js
> +    capacity: capacity,
Capacity I believe is what the label I used but its really just the size of the viewport being changed so that when updating the viewport it knows how much it should contain.

2022-05-10 23:43 UTC, scholarsmate commented on src/omega_edit/client.ts
> +              change.setLength(message.capacity)
CreateViewport sets the offset and capacity of the viewport.  Is the purpose of this function to update a viewport with the change from the subscription?  If so, then this might be fine.

2022-05-10 23:45 UTC, scholarsmate commented on src/omega_edit/scripts/omega_edit.js
> +    capacity: capacity,
Okay.  Where in the code are changes getting sent to Ωedit?

2022-05-10 23:46 UTC, Shanedell commented on src/omega_edit/client.ts
> +              change.setLength(message.capacity)
Yeah so this basically records the change setting offset and length of change to be the exact values for the viewport being updated then it submits the change to the server

2022-05-10 23:47 UTC, Shanedell commented on src/omega_edit/scripts/omega_edit.js
> +    capacity: capacity,
`client.submitChange` is where the change is being send to the server

2022-05-10 23:53 UTC, scholarsmate commented on src/omega_edit/client.ts
> +              change.setLength(message.capacity)
The way I'm reading this is when a viewport receives a change from the user, the whole viewport is being sent to Ωedit as a single OVERWRITE change.  If a user inserts the letter 'a' into a viewport, this sends the whole viewport back to Ωedit as a single overwrite instead of just the offset and the letter 'a' as an INSERT.  This is going to waste a lot of memory doing it this way.

2022-05-10 23:59 UTC, Shanedell commented on src/omega_edit/client.ts
> +              change.setLength(message.capacity)
Yeah I am in this process right now of trying to work this out, it seems like it will heavily depend on the selection/cursor point right? So if the position is just 1 you assume inset or delete right? Then if its greater than 1 you assume overwrite?

2022-05-10 23:59 UTC, scholarsmate commented on src/omega_edit/client.ts
> +              change.setLength(message.capacity)
What we want from VSCode here is the offset inside the viewport, the mode (insert, or overwrite) and the key being pressed.  If the key is delete, we delete 1 byte from the current offset.  If the mode is insert, we insert the key pressed at that offset, and if the mode is overwrite, then the byte at that offset is overwritten by the key pressed.  Ωedit will update it model and subscribers will get their refreshed data sent to them.

2022-05-15 23:45 UTC, Shanedell commented
@scholarsmate Everything now works as expected I believe. Insert happens when nothing is selected and a key is pressed, delete happens backspace or delete is pressed, overwrite happens when something is selected and a key is pressed (just deletes the selected portion than adds the character of the key pressed)

2022-05-18 01:00 UTC, Shanedell commented
@scholarsmate I can update this to use the wrapper code you made in omega-edit if we get into a package

2022-05-20 00:40 UTC, scholarsmate approved these changes
This patch includes workarounds to overwrite, undo, and redo that we need to fix properly before a public release.

2022-05-20 01:12 UTC, merged